### ISSUE TITLE
World Scale UV: RuntimeError("Find more than 2 texture nodes")

### ISSUE THREAD

**Issue by seancyh** [nutti/Magic-UV#107]
OS: [Windows 10]
Blender version: [2.8 Beta]
Add-on version: [6.0]

hi @nutti ,

I am having problem when using the World Scale UV in 2.8 Beta.
While I am trying to measure the UV, it give me this error, saying it has more than 2 texture nodes (PBR)

```
Traceback (most recent call last):
  File "C:\Users\user\Desktop\blender-2.80-c6cbcf83d015-win64\blender-2.80.0-git.c6cbcf83d015-windows64\2.80\scripts\addons\magic_uv\op\world_scale_uv.py", line 294, in execute
    uv_area, mesh_area, density = _measure_wsuv_info(obj)
  File "C:\Users\user\Desktop\blender-2.80-c6cbcf83d015-win64\blender-2.80.0-git.c6cbcf83d015-windows64\2.80\scripts\addons\magic_uv\op\world_scale_uv.py", line 67, in _measure_wsuv_info
    uv_area = common.measure_uv_area(obj, tex_size)
  File "C:\Users\user\Desktop\blender-2.80-c6cbcf83d015-win64\blender-2.80.0-git.c6cbcf83d015-windows64\2.80\scripts\addons\magic_uv\common.py", line 444, in measure_uv_area
    img = find_image(obj, f, tex_layer)
  File "C:\Users\user\Desktop\blender-2.80-c6cbcf83d015-win64\blender-2.80.0-git.c6cbcf83d015-windows64\2.80\scripts\addons\magic_uv\common.py", line 411, in find_image
    raise RuntimeError("Find more than 2 texture nodes")
RuntimeError: Find more than 2 texture nodes
```

![2nodesplus](https://user-images.githubusercontent.com/47655058/52838775-bf584300-312e-11e9-86e7-801a1ee07c64.jpg)

But when I am using only one texture nodes, it works fine. Can you please take a look?

![1node](https://user-images.githubusercontent.com/47655058/52838785-c7b07e00-312e-11e9-9e4f-2d7611c3395e.jpg)

I am not sure if I am using it wrong in this version, but in 2.79, it has no issue.

thanks a lot for the great work
Sean

**Comment by nutti** [comment]
Thanks for reporting issue.
Current version can not apply World Scale UV if there are more than 2 Texture Node.

But I think it is good to extend to the situation there is more than 2 Texture Node.
I will tackle to fix this.

**Comment by seancyh** [comment]
Thanks for the reply, so right now there's no way to use PBR material? because that requires more than 2 texture nodes most of the time. Looking forward for your fix.

**Comment by nutti** [comment]
@seancyh 

Very sorry for late response.
I fixed this issue now, and you can use World Scale UV with more than 2 texture nodes.
It's in develop branch for now, but I will move to master as well after I finished other task.
