### ISSUE TITLE
updater for linux 

### ISSUE THREAD

**Issue by ab-in** [nutti/Magic-UV#112]
Traceback (most recent call last):
  File "/usr/share/blender/2.80/scripts/addons/magic_uv/updater.py", line 72, in execute
    updater.update(self.branch_name)
  File "/usr/share/blender/2.80/scripts/addons/magic_uv/utils/addon_updator.py", line 314, in update
    _make_workspace(self.__config.addon_directory)
  File "/usr/share/blender/2.80/scripts/addons/magic_uv/utils/addon_updator.py", line 83, in _make_workspace
    os.mkdir(dir_path)
PermissionError: [Errno 13] Permission denied: '/usr/share/blender/2.80/scripts/addons/addon_updator_workspace'

location: <unknown location>:-1

**Comment by nutti** [comment]
This bug is already fixed. 4890518e1b6e7e2401a07c85b4c57b62b67f016f
