### ISSUE TITLE
Traceback error with MagicUV in 2.81

### ISSUE THREAD

**Issue by handsomeboy256** [nutti/Magic-UV#119]
**System Information**
  
* OS: Windows 10
* Blender version: 2.81
* Add-on version: 6.2.0

**Expected behavior**  
Smooth or pack UVs, use magicUV functions.

**Description about the bug**  
When using Magic UV smooth, straighten, or pack it has a traceback error. 

**Screenshots/Files** [Optional]  
![image](https://user-images.githubusercontent.com/58191000/69576769-d9f2fe80-0f81-11ea-9ea4-ec6ebda624de.png)

**Additional comments** [Optional]
Perhaps an issue with 2.81?

**Comment by josephbburg** [comment]
I have this problem, too. It's the recursion limit on your Python that causes it- https://stackoverflow.com/questions/3323001/what-is-the-maximum-recursion-depth-in-python-and-how-to-increase-it

**Comment by davidmorning** [comment]
Getting the same issue with Blender 2.82, is there a work around with the above link? I tried tweaking the script, but even adding the sys.setrecursionlimit function in the functions listed above didn't seem to make a difference to the limit it hit

**Comment by ApeInOuterSpace** [comment]
I have a similar issue in Blender 2.83 on Fedora 31. Would be great if this bug could be fixed.

`
bpy.ops.uv.muv_align_uv_straighten(transmission=False, select=False, vertical=False, horizontal=False, mesh_infl=0)

Traceback (most recent call last):
  File "/usr/share/blender/2.82/scripts/addons/magic_uv/op/align_uv.py", line 597, in execute
    loop_seqs, error = common.get_loop_sequences(bm, uv_layer)
  File "/usr/share/blender/2.82/scripts/addons/magic_uv/common.py", line 780, in get_loop_sequences
    isl_info = get_island_info_from_bmesh(bm, False)
  File "/usr/share/blender/2.82/scripts/addons/magic_uv/common.py", line 307, in get_island_info_from_bmesh
    return get_island_info_from_faces(bm, selected_faces, uv_layer)
  File "/usr/share/blender/2.82/scripts/addons/magic_uv/common.py", line 314, in get_island_info_from_faces
    uv_island_lists = __get_island(bm, ftv, vtf)
  File "/usr/share/blender/2.82/scripts/addons/magic_uv/common.py", line 269, in __get_island
    face_to_verts, vert_to_faces)
  File "/usr/share/blender/2.82/scripts/addons/magic_uv/common.py", line 255, in __parse_island
    vert_to_faces)
  File "/usr/share/blender/2.82/scripts/addons/magic_uv/common.py", line 255, in __parse_island
    vert_to_faces)
  File "/usr/share/blender/2.82/scripts/addons/magic_uv/common.py", line 255, in __parse_island
    vert_to_faces)
  [Previous line repeated 989 more times]
  File "/usr/share/blender/2.82/scripts/addons/magic_uv/common.py", line 251, in __parse_island
    connected_faces = vert_to_faces[v]
RecursionError: maximum recursion depth exceeded in comparison

location: <unknown location>:-1
`

**Comment by nutti** [comment]
Hi, there!

Thanks for your feedback!
I think this issue must be resolved, and will tackle to fix it.

**Comment by nutti** [comment]
Thanks for reporting this issue, and sorry for late response.

This issue is fixed, and available at [unstable](https://github.com/nutti/Magic-UV/archive/develop.zip) version.
This patch will be available at next release.
