### ISSUE TITLE
Select Overlapped or Flipped results in TypeError: zip argument #1 must support iteration

### ISSUE THREAD

**Issue by Fak3** [nutti/Magic-UV#129]
**System Information**
  
* OS: Linux
* Blender version: 2.83
* Add-on version: git master

Steps to reproduce:

* open this blend file https://drive.google.com/file/d/1U2MhaL0f6Ry6SB4c0YYDyIG00xbzk9qf/view?usp=sharing
* in the uv editor, open N menu, there open the magic uv tab -> UV manipulation -> Select UV
* click "Overlapped" or "Flipped"

result:
```
Traceback (most recent call last):
  File "/home/z/soft/blender-2.83.0-ec26260132b4-linux64/2.83/scripts/addons/magic_uv/op/select_uv.py", line 106, in execute
    uv_layer, 'FACE')
  File "/home/z/soft/blender-2.83.0-ec26260132b4-linux64/2.83/scripts/addons/magic_uv/common.py", line 1117, in get_overlapped_uv_info
    for bm, uv_layer, faces in zip(bm_list, uv_layer_list, faces_list):
TypeError: zip argument #1 must support iteration
```

**Comment by nutti** [comment]
@Fak3 

Oops. This issue comes from #115 .
I forgot fixing this feature.
Thanks. I fixed it and merged to master branch.
