### ISSUE TITLE
Align UV: More then 2 UVs must be selected.

### ISSUE THREAD

**Issue by MostHostLA** [nutti/Magic-UV#135]
Following exactly this procedure:
https://www.youtube.com/watch?v=BKZX3Xac7X4&t=724s

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\magic_uv\op\align_uv.py", line 597, in execute
    loop_seqs, error = common.get_loop_sequences(bm, uv_layer)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\magic_uv\common.py", line 780, in get_loop_sequences
    isl_info = get_island_info_from_bmesh(bm, False)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\magic_uv\common.py", line 307, in get_island_info_from_bmesh
    return get_island_info_from_faces(bm, selected_faces, uv_layer)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\magic_uv\common.py", line 314, in get_island_info_from_faces
    uv_island_lists = __get_island(bm, ftv, vtf)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\magic_uv\common.py", line 269, in __get_island
    face_to_verts, vert_to_faces)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\magic_uv\common.py", line 255, in __parse_island
    vert_to_faces)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\magic_uv\common.py", line 255, in __parse_island
    vert_to_faces)
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\magic_uv\common.py", line 255, in __parse_island
    vert_to_faces)
  [Previous line repeated 989 more times]
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\magic_uv\common.py", line 251, in __parse_island
    connected_faces = vert_to_faces[v]
RecursionError: maximum recursion depth exceeded in comparison

Unchecking "transmission" seems to run, albeit it has already taken 2 minutes...

**Comment by nutti** [comment]
@MostHostLA 

I think this is same as #128 #131 .
`RecursionError` is already fixed and will be released in v6.3.

Now, this is a duplication of #131, I will close this issue.
Could you follow #131 instead?
