### ISSUE TITLE
RecursionError any button, I press

### ISSUE THREAD

**Issue by smarchevsky** [nutti/Magic-UV#142]
**System Information**
  Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\magic_uv\op\align_uv.py", line 390, in execute
    loop_seqs, error = common.get_loop_sequences(bm, uv_layer, True)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\magic_uv\common.py", line 780, in get_loop_sequences
    isl_info = get_island_info_from_bmesh(bm, False)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\magic_uv\common.py", line 307, in get_island_info_from_bmesh
    return get_island_info_from_faces(bm, selected_faces, uv_layer)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\magic_uv\common.py", line 314, in get_island_info_from_faces
    uv_island_lists = __get_island(bm, ftv, vtf)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\magic_uv\common.py", line 269, in __get_island
    face_to_verts, vert_to_faces)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\magic_uv\common.py", line 255, in __parse_island
    vert_to_faces)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\magic_uv\common.py", line 255, in __parse_island
    vert_to_faces)
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\magic_uv\common.py", line 255, in __parse_island
    vert_to_faces)
  [Previous line repeated 990 more times]
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\magic_uv\common.py", line 248, in __parse_island
    faces_left.remove(face_idx)
RecursionError: maximum recursion depth exceeded in comparison

location: <unknown location>:-1

**Comment by nutti** [comment]
@smarchevsky 

Hi,
This error is already fixed in v6.3.
If you don't use another version, please reopen this issue.

https://github.com/nutti/Magic-UV/issues/128
