### ISSUE TITLE
UV Manipulation errors

### ISSUE THREAD

**Issue by schroef** [nutti/Magic-UV#79]
v5.0
OSX
bl 2.78

I get this error when i try UV Manipulation > circle
`Traceback (most recent call last):
  File "/Users/PromotieSpullen/Library/Application Support/Blender/2.78/scripts/addons/uv_magic_uv/op/align_uv.py", line 146, in execute
    loop_seqs, error = get_closed_loop_sequences(bm, uv_layer)
  File "/Users/PromotieSpullen/Library/Application Support/Blender/2.78/scripts/addons/uv_magic_uv/op/align_uv.py", line 52, in get_closed_loop_sequences
    loop_pairs = common.get_loop_pairs(first_loop, uv_layer)
AttributeError: module 'uv_magic_uv.common' has no attribute 'get_loop_pairs'

location: <unknown location>:-1

`

Also your version behaves really different than the uv_tools version. Mesh influence is in the smooth tab. Whereas with uv_tools it also influenced when doing straighten action.

The straighten op doesnt work when wanting to straighten en line in the middle, seems to only work on outer edges.

Align UV shows this error
`Traceback (most recent call last):
  File "/Users/PromotieSpullen/Library/Application Support/Blender/2.78/scripts/addons/uv_magic_uv/op/align_uv.py", line 146, in execute
    loop_seqs, error = get_closed_loop_sequences(bm, uv_layer)
  File "/Users/PromotieSpullen/Library/Application Support/Blender/2.78/scripts/addons/uv_magic_uv/op/align_uv.py", line 52, in get_closed_loop_sequences
    loop_pairs = common.get_loop_pairs(first_loop, uv_layer)
AttributeError: module 'uv_magic_uv.common' has no attribute 'get_loop_pairs'

location: <unknown location>:-1

Traceback (most recent call last):
  File "/Users/PromotieSpullen/Library/Application Support/Blender/2.78/scripts/addons/uv_magic_uv/ui/uvedit_editor_enhance.py", line 105, in draw
    if sc.muv_uvcloc_enabled:
AttributeError: 'Scene' object has no attribute 'muv_uvcloc_enabled'

location: <unknown location>:-1

`

**Comment by nutti** [comment]
> Align UV shows this error

This has already fixed.
Please try to use unstable version for now.

> Also your version behaves really different than the uv_tools version.

Sorry, I can not read the original source which is written in Chinese.
So I implemented UV_Tool while I confirm the spec to original author.
Maybe, I think some features behave incorrectly.
Please feedback about the difference between Magic UV and UV_Tool if you have any other ideas.

**Comment by nutti** [comment]
This is a list of the issues reported in this issue

 - [x] (Align UV) Failed to execute Circle operation
 - [x] (UV Cursor Location) Not show menu
 - [ ] (Align UV) Add Mesh Influence option to align UV
 - [ ] (Align UV) Extend to inter edge to align UV

**Comment by nutti** [comment]
> I get this error when i try UV Manipulation > circle

Fixed this error. it's in the develop branch

**Comment by nutti** [comment]
> (Align UV) Add Mesh Influence option to align UV

This issue has already fixed.
